-- Import every target from Agora/targets
import Targets.listReduceoptionEqSingletonIffzero
import Targets.powerseriesOneSubPowAddMulInvonesubpowValEqOneSubPowzero
import Targets.contmdiffmapCoeOnezero
import Targets.setlikeCovbyIffzero
import Targets.canonicallyorderedaddMulPosone
import Targets.algebraEtaleIffExistsAlgequivProdzero
import Targets.canonicallyorderedaddPowPoszero
import Targets.strictconvexspaceOfStrictconvexUnitclosedballzero
import Targets.isapproximatesubgroupPowInterPowCovbysmulSqInterSqzero
import Targets.derivNormOfrealCpowzero
import Targets.isapproximatesubgroupCardMulSelfLeone
import Targets.setlikeIscoatomIffone
import Targets.padicintValuationPowone
import Targets.polynomialHilbertpolyEqZeroOfLeRootmultiplicityOneone
import Targets.charactermoduleDualInjectiveIffSurjectivezero
import Targets.padicintNormEqZpowNegValuationzero
