-- Import every target from Agora/targets
import Targets.powerseriesOneSubPowAddMulInvonesubpowValEqOneSubPowzero
import Targets.isapproximatesubgroupPowInterPowCovbysmulSqInterSqzero
import Targets.padicintValuationPowone
import Targets.padicintNormEqZpowNegValuationzero
